

# Use official nginx image as the base image
FROM nginx:latest

COPY ./default.conf /etc/nginx/conf.d/default.conf
# Copy the build output to replace the default nginx contents.
# COPY --from=build /usr/local/app/dist/frontend /usr/share/nginx/html